name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa automaticamente todos os dias
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ismapereira  # Seu nome de usuário no GitHub

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
