name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa automaticamente todos os dias
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ismapereira  # Seu nome de usuário no GitHub
          outputs: dist/github-contribution-grid-snake.svg  # Define o caminho correto para o arquivo gerado
          snakeColor: "#2196F3"  # Cor para a cobrinha (pode alterar para qualquer cor)
          gridColor: "#424242"  # Cor dos quadrados de fundo (pode alterar também)

      - name: Configurar o Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"  # Configura o e-mail para commits automáticos

      - name: Atualizar branch output
        run: |
          git fetch origin output  # Atualiza a branch output remotamente
          git checkout output      # Muda para a branch output
          git pull origin output   # Faz o pull para integrar os commits
          git add .                # Adiciona o arquivo gerado
          git commit -m "Add snake animation"  # Faz o commit
          git push origin output   # Faz o push da branch output

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output  # A branch de publicação é a output
          publish_dir: ./dist  # O diretório a ser publicado é o ./dist
