name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente

  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ismapereira
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload para o GitHub Pages
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
